name: Hugo build-on-change deploying to gcloud storage bucket
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jakejarvis/hugo-build-action@v0.111.3
      with:
        args: --minify --buildDrafts
    - id: 'google-auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: 'strategichopes-web-writer@awaylab.iam.gserviceaccount.com'
        credentials_json: ${{secrets.GCLOUD_JSON_KEY}}
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: './public'
        destination: 'web-content.www.strategichopes.co'
