jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jakejarvis/hugo-build-action@v0.111.3
      with:
        args: --minify --buildDrafts
    - uses: actions/upload-artifact@v3.1.3
      with:
        name: www-data-${{ github.sha }}
        path: './public'
        if-no-files-found: error
        retention-days: 5
